using System;
using System.Linq;
using BehavioralPatterns.Visitor.DataProcessors;

namespace BehavioralPatterns.Visitor.Visitors {
    public class MarketResearchReportVisitor : IVisitor<MarketResearchReport> {
        public MarketResearchReport Visit(FloristDataProcessor processor) {
            var customerProfiles = processor.GetMonthlyCustomerProfiles();
            var customerAges = customerProfiles.Select(customer => customer.Age).ToList();
            var averageAge = (decimal) Math.Round(customerAges.Average(), 2);
            var youngestAge = customerAges.Min();
            var oldestAge = customerAges.Max();

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Visiting Florist for Generating Market Report");
            Console.ResetColor();

            return new MarketResearchReport {
                NumberOfSamples = customerProfiles.Count,
                AverageAge = averageAge,
                OldestCustomer = oldestAge,
                YoungestCustomer = youngestAge
            };
        }

        public MarketResearchReport Visit(BakeryDataProcessor order) {
            var customerProfiles = order.GetMonthlyCustomerProfiles();
            var customerAges = customerProfiles.Select(customer => customer.Age).ToList();
            var averageAge = (decimal) Math.Round(customerAges.Average(), 2);
            var youngestAge = customerAges.Min();
            var oldestAge = customerAges.Max();

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Visiting Bakery for Generating Market Report");
            Console.ResetColor();

            return new MarketResearchReport {
                NumberOfSamples = customerProfiles.Count,
                AverageAge = averageAge,
                OldestCustomer = oldestAge,
                YoungestCustomer = youngestAge
            };
        }

        public MarketResearchReport Visit(FarmerDataProcessor order) {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("Market research is not yet available for Farm Data");
            Console.ResetColor();
            Console.WriteLine("\n");
            return null;
        }
    }

    public class MarketResearchReport : Report {
        public MarketResearchReport() {
            CreatedBy = "MarketResearchRobot";
            CreatedOn = DateTime.UtcNow;
        }
        public int NumberOfSamples { get; set; }
        public decimal AverageAge { get; set; }
        public int OldestCustomer { get; set; }
        public int YoungestCustomer { get; set; }
        public override void Print() {
            Console.ForegroundColor = ConsoleColor.DarkCyan;
            Console.WriteLine($"=== 📊 Market Research for {CreatedOn} 📊 ===");
            Console.WriteLine($"=== Generated By: {CreatedBy} ===");
            Console.WriteLine($"- Number of Samples Today: {NumberOfSamples}");
            Console.WriteLine($"- Average Customer Age: {AverageAge}");
            Console.WriteLine($"- Oldest Customer: {OldestCustomer}");
            Console.WriteLine($"- Youngest Customer: {YoungestCustomer}");
            Console.ResetColor();
            Console.WriteLine("\n");
        }
    }
}
