using System;
using System.Linq;
using BehavioralPatterns.Visitor.Components;
using RealisticDependencies;

namespace BehavioralPatterns.Visitor.Visitors {
    public class SaleDataVisitor : IVisitor<SalesReport> {
        private readonly ISendsEmails _emailer;

        public SaleDataVisitor(ISendsEmails emailer) {
            _emailer = emailer;
        }

        /// <summary>
        /// Here the Florist Co-Op wants to be emailed when we run the Sales Report
        /// The FloristDataProcessor doesn't know anything other than how to generate
        /// the data it already works with, and a method enabling it to be "visited."
        /// </summary>
        /// <param name="processor"></param>
        /// <returns></returns>
        public SalesReport Visit(FloristDataProcessor processor) {
            Console.ForegroundColor = ConsoleColor.Magenta;
            Console.WriteLine("Visiting Florist Data for Generating Sales Report");
            Console.WriteLine("Emailing Florist Co-Op Managers about today's sales");
            var sales = processor.GetDailyOrderAmounts();
            var email = new EmailMessage("managers@example.com", $"Number of sales: {sales.Count}");
            _emailer.SendMessage(email);
            Console.ResetColor();
            return new SalesReport(DateTime.UtcNow, sales.Sum());
        }

        public SalesReport Visit(BakeryDataProcessor processor) {
            Console.ForegroundColor = ConsoleColor.Magenta;
            Console.WriteLine("Visiting Bakery for Generating Sales Report");
            var sales = processor.GetDailyOrderAmounts();
            Console.ResetColor();
            return new SalesReport(DateTime.UtcNow, sales.Sum());
        }

        public SalesReport Visit(FarmerDataProcessor processor) {
            Console.ForegroundColor = ConsoleColor.Magenta;
            Console.WriteLine("Visiting Farmer for Generating Sales Report");
            var sales = processor.GetDailyOrderAmounts();
            Console.ResetColor();
            return new SalesReport(DateTime.UtcNow, sales.Sum());
        }
    }

    public class SalesReport : Report {
        public SalesReport(DateTime date, decimal totalSales) {
            CreatedBy = "SalesDataRobot";
            CreatedOn = date;
            TotalSales = totalSales;
        }

        public decimal TotalSales { get; set; }

        public override void Print() {
            Console.ForegroundColor = ConsoleColor.DarkCyan;
            Console.WriteLine($"=== 💸 Sales Data for {CreatedOn} 💸 ===");
            Console.WriteLine($"=== Generated By: {CreatedBy} ===");
            Console.WriteLine($"- Total Sales Today: ${TotalSales}");
        }
    }
}
